### ISSUE TITLE
Nested configuration

### ISSUE THREAD

**Issue by sylvainlap** [feathersjs/feathers-configuration#38]
Hi,

It is said that `feathers-configuration` is a simple wrapper on node-config. However, with node-config, if you have nested configuration, like that:

```
{
  "Customer": {
    "dbConfig": {
      "host": "prod-db-server"
    },
    "credit": {
      "initialDays": 30
    }
  }
}
```

you can access the `host` attribute by using `config.get('Customer.dbConfig.host')`. However, with `feathers-configuration`, this dot notation do not work.

**Comment by daffl** [comment]
Mainly because the underlying Express [app.set](http://expressjs.com/en/4x/api.html#app.set) and [app.get()](http://expressjs.com/en/4x/api.html#app.get) don't support it. It'll be `app.get('Customer').config.host`  instead. You could also `require('config')` directly and use it the way it is described.

**Comment by sylvainlap** [comment]
OK thanks. I close the issue.
