### ISSUE TITLE
Needs an escape character

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-configuration#4]
There needs to be an escape character (most likely `\`) if you do not want to convert a configuration value. E.g.

```js
{
  "env": "\\NODE_ENV",
  "path": "\\./home"
}
```

Should set `env` to the actual string `NODE_ENV` and `path` to `./home`

**Comment by matb33** [comment]
This causes issues when trying to pass along PORT to IIS. An example PORT can look like this:
```
\\.\pipe\ad443a91-dc7e-4222-a95a-6e64a2554faf
```

**Comment by daffl** [comment]
Why? Shouldn't `\\\\.\pipe\ad443a91-dc7e-4222-a95a-6e64a2554faf` work?

**Comment by matb33** [comment]
Because IIS populates the PORT env variable

**Comment by daffl** [comment]
I'm not following. If you set that string as the PORT environment variable it won't be escaped (see https://github.com/feathersjs/feathers-configuration/blob/master/src/index.js#L26).

**Comment by matb33** [comment]
iisnode will automatically set the environment variable `PORT` with a value that looks like`\\.\pipe\ad443a91-dc7e-4222-a95a-6e64a2554faf`. The user does not set this. The value could change. IIS likely generates this thing and iisnode likely sets it as the `PORT` environment variable for node to consume.

iisnode then assumes you will run your server on port `process.env.PORT`.

That being said, if one wants to leverage `feathers-configuration` and is stuck with having to use iisnode, they can't pass along `PORT` without the leading backslash being removed.

I've implemented a hack workaround to get us through this situation. I'm not entirely sure why this package is changing the values being passed through -- I assume there's a good reason, but it was certainly surprising to have environment variable values changed out from underneath us.

**Comment by daffl** [comment]
I can't test this on Windows but I just verified on Mac OS that an environment variable with two leading backslashes will not be escaped.

**Comment by matb33** [comment]
Are you saying that the code here did not remove the first backslash?
https://github.com/feathersjs/feathers-configuration/blob/master/src/index.js#L23-L24

It's sounding more and more like there's a miscommunication going on. I can only continue stressing that the `PORT` environment variable is set automatically by iisnode. I can't go and change it and add extra backslashes to compensate because the value is automatically generated.

I think perhaps you are confusing this issue with the escaping functionality itself. Your escaping functionality is working as you intended. What I'm trying to bring to light is that the value of an environment variable with leading backslashes will have its first backslash trimmed off.

Example:

1. A node management process (such as iisnode) automatically sets up some environment variables, among them being `PORT` with the value `\\.\pipe\ad443a91-dc7e-4222-a95a-6e64a2554faf` (this CANNOT be changed!)

2. A configuration json file is set-up that looks like:
```
{
   "port": "PORT"
}
```

3. A boot-up script that looks like:
```
import feathers from 'feathers'
import configuration from 'feathers-configuration'
import { createServer } from 'https'

const app = feathers()
app.configure(configuration())
const port = app.get('port')
const server = createServer({}, app).listen(port)
```

In such a scenario, the environment variable `PORT` will be changed from
```
\\.\pipe\ad443a91-dc7e-4222-a95a-6e64a2554faf
```
to
```
\.\pipe\ad443a91-dc7e-4222-a95a-6e64a2554faf
```

**Comment by daffl** [comment]
That's what I am trying to say. The environment variable will not be read until https://github.com/feathersjs/feathers-configuration/blob/master/src/index.js#L26 when the part of the code that removes the leading slash is already skipped (because `'PORT'.indexOf('\\') !== 0`).

I was able to confirm this again on Mac OS by creating a new folder with an `app.js` like:

```js
const feathers = require('feathers');
const configuration = require('feathers-configuration');

const app = feathers().configure(configuration());

console.log(app.get('test'))
```

A `config/default.json` like:

```json
```

**Comment by matb33** [comment]
OK, I see it -- apologies.

That leading backslash is likely getting dropped elsewhere, probably as part of our code.

When I looked at your code, what threw me off was the var name `value`, and how if we were to suppose `value` was the environment variable's value, that little bit:
```
          if (value.indexOf('\\') === 0) {
            value = value.replace('\\', '');
          } else {
```
would have actually stripped leading backslashes, so it was a perfect combination of red herrings...

Thanks for your patience @daffl
